# Create a `Dockerfile`

# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jdk-slim

# Set the working directory
WORKDIR /app

# Add the project files to the Docker image
ADD . /app

# Package the application
RUN ./mvnw package

# Run the application
CMD ["java", "-jar", "target/receipt-processor-0.0.1-SNAPSHOT.jar"]


# Running the Application

docker build -t receipt-processor .
docker run -p 8080:8080 receipt-processor
